name = "gdeepseries"
description = "Series expansions for the 3D infinite-depth free-surface Green function."
version = "0.1.0"
license = "MIT"
author = "Rodrigo Castro"
maintainer = "rodpcastro18@gmail.com"
copyright = "Copyright 2025 Rodrigo Castro"
categories = ["mathematics", "scientific-computing", "hydrodynamics"]
homepage = "https://github.com/rodpcastro/gdeepseries"

[install]
library = true

[dependencies]
colspecf = {git = "https://github.com/rodpcastro/colspecf.git"}

[dev-dependencies]
test-drive = {git = "https://github.com/fortran-lang/test-drive.git"}
stdlib = {git="https://github.com/fortran-lang/stdlib", branch="stdlib-fpm"}
